=== m-o-z-i/navigation-viewing-framework/configs/config.dtd
<!--
  Oculus-Powerwall Framework
  Document Type Definition for XML configuration files

  Naming convention for files:
  device_types_used_(desktopusers)(powerwallusers)(ovrusers).xml
  -->

  <!ELEMENT setup (global, device+, user+)>
  
  <!ELEMENT global (transmitteroffset, notrackingposition, groundfollowing)>
  <!ELEMENT transmitteroffset (x, y, z)>
  <!ELEMENT notrackingposition (x, y, z)>
  <!ELEMENT groundfollowing (activated, raystartheight)>
  <!ELEMENT activated (#PCDATA)>
  <!ELEMENT raystartheight (#PCDATA)>
  
  <!ELEMENT device (type, inputsensor, trackingstation, platformpos, platformrot)>
  <!ELEMENT type (#PCDATA)>
  <!ELEMENT inputsensor (#PCDATA)>
  <!ELEMENT trackingstation (#PCDATA)>
  <!ELEMENT platformpos (x, y, z)>
  <!ELEMENT x (#PCDATA)>
  <!ELEMENT y (#PCDATA)>
  <!ELEMENT z (#PCDATA)>
  <!ELEMENT platformrot (yaw)>
  <!ELEMENT yaw (#PCDATA)>
  <!ELEMENT platformsize (width, depth)>
  <!ELEMENT width (#PCDATA)>
  <!ELEMENT depth (#PCDATA)>

  <!ELEMENT user (type, headtrackingstation, startplatform)>
  <!ELEMENT headtrackingstation (#PCDATA)>
  <!ELEMENT startplatform (#PCDATA)>
  <!ELEMENT warnings (#PCDATA)>

=== m-o-z-i/navigation-viewing-framework/configs/hit_001.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE setup SYSTEM "config.dtd">

<setup>

  <global>
    
    <transmitteroffset>
      <x>0.0</x>
      <y>0.0043</y>
      <z>1.6</z>
    </transmitteroffset>

    <notrackingposition>
      <x>0.0</x>
      <y>1.75</y>
      <z>1.5</z>
    </notrackingposition>

    <groundfollowing>
      <activated>True</activated>
      <raystartheight>0.75</raystartheight>
    </groundfollowing>

    <movementtraces>True</movementtraces>
    <animatecoupling>True</animatecoupling>

  </global>

  <device>

    <hostname>nestor</hostname>

    <type>XBoxController</type>

    <inputsensor>device-xbox-1</inputsensor>

    <trackingstation>tracking-oculus-front</trackingstation>

    <platformpos>
      <x>2.0</x>
      <y>0.0</y>
      <z>12.0</z>
    </platformpos>

    <platformrot>
      <yaw>0.0</yaw>
    </platformrot>

    <platformsize>
      <width>3.8</width>
      <depth>3.6</depth>
    </platformsize>

  </device>

  <!-- First OVR User -->

  <user>

    <type>OVRUser</type>

    <headtrackingstation>tracking-oculus-front</headtrackingstation>

    <startplatform>0</startplatform>

    <warnings>False</warnings>

    <display>:0.0</display>

  </user>

<<<<<<< HEAD
  <!-- Second OVR User -->
=======
>>>>>>> master

</setup>

=== m-o-z-i/navigation-viewing-framework/configs/oldspheron_010.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE setup SYSTEM "config.dtd">

<setup>
  
  <global>
    
    <transmitteroffset>
      <x>0.0</x>
      <y>0.0043</y>
      <z>1.6</z>
    </transmitteroffset>

    <notrackingposition>
      <x>0.0</x>
      <y>1.75</y>
      <z>1.5</z>
    </notrackingposition>

    <groundfollowing>
      <activated>True</activated>
      <raystartheight>0.75</raystartheight>
    </groundfollowing>

    <animatecoupling>True</animatecoupling>
    <movementtraces>True</movementtraces>

  </global>
  
  <device>

    <hostname>nestor</hostname>

    <type>OldSpheron</type>

    <inputsensor>device-old-spheron</inputsensor>

    <trackingstation>tracking-old-spheron</trackingstation>

    <platformpos>
      <x>-2.0</x>
      <y>0.0</y>
      <z>12.0</z>
    </platformpos>

    <platformrot>
      <yaw>0.0</yaw>
    </platformrot>

    <platformsize>
      <width>3.8</width>
      <depth>3.6</depth>
    </platformsize>

  </device>

  <!-- First Power Wall User -->
  <user>

    <type>PowerWallUser</type>

    <headtrackingstation>tracking-glasses-1</headtrackingstation>

    <startplatform>0</startplatform>

    <warnings>True</warnings>

    <display>:0.0</display>

  </user>
  
   

</setup>

=== m-o-z-i/navigation-viewing-framework/configs/two_ovr_one_desktop.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE setup SYSTEM "config.dtd">

<setup>

  <global>
    
    <transmitteroffset>
      <x>0.0</x>
      <y>0.0043</y>
      <z>1.6</z>
    </transmitteroffset>

    <notrackingposition>
      <x>0.0</x>
      <y>1.75</y>
      <z>1.5</z>
    </notrackingposition>

    <groundfollowing>
      <activated>True</activated>
      <raystartheight>0.75</raystartheight>
    </groundfollowing>

    <animatecoupling>False</animatecoupling>
    <movementtraces>False</movementtraces>

  </global>

  <device>

    <type>XBoxController</type>

    <inputsensor>device-xbox-1</inputsensor>

    <trackingstation>tracking-oculus-stag</trackingstation>

    <platformpos>
      <x>0.0</x>
      <y>0.0</y>
      <z>6.0</z>
    </platformpos>

    <platformrot>
      <yaw>0.0</yaw>
    </platformrot>

    <platformsize>
      <width>3.8</width>
      <depth>3.6</depth>
    </platformsize>

  </device>

  <device>

    <type>XBoxController</type>

    <inputsensor>device-xbox-2</inputsensor>

    <trackingstation>tracking-oculus-front</trackingstation>

    <platformpos>
      <x>0.0</x>
      <y>0.0</y>
      <z>12.0</z>
    </platformpos>

    <platformrot>
      <yaw>0.0</yaw>
    </platformrot>

    <platformsize>
      <width>3.8</width>
      <depth>3.6</depth>
    </platformsize>

  </device>

  <device>

    <type>Spacemouse</type>

    <inputsensor>device-spacemouse</inputsensor>

    <platformpos>
      <x>0.0</x>
      <y>0.0</y>
      <z>17.0</z>
    </platformpos>

    <platformrot>
      <yaw>0.0</yaw>
    </platformrot>

  </device>
        

  <!-- First OVR User -->
  
  <user>

    <type>OVRUser</type>

    <headtrackingstation>tracking-oculus-stag</headtrackingstation>

    <startplatform>0</startplatform>

    <warnings>False</warnings>

  </user>

  <!-- Second OVR User -->
  
  <user>

    <type>OVRUser</type>

    <headtrackingstation>tracking-oculus-front</headtrackingstation>

    <startplatform>1</startplatform>

    <warnings>False</warnings>

  </user>

  <!-- First Desktop User -->
  
  <user>

    <type>DesktopUser</type>

    <startplatform>2</startplatform>

    <windowsize>
      <width>1280</width>
      <height>800</height>
    </windowsize>

    <screensize>
      <width>1.06</width>
      <height>0.74</height>
    </screensize>

  </user>
   

</setup>
